language: python
python:
  - "3.4"
  - "3.5"
script: 
  - "python3 -m unittest discover"
  - "python3 inspiderweb.py --help"
  - "python3 inspiderweb.py --h"
  - "python3 inspiderweb.py --database db/test.pickle"
  - "python3 inspiderweb.py -d db/test.pickle"
  - "python3 inspiderweb.py --database db/test.pickle --seeds seeds/example_minimal.txt --updateseeds bib,refs"
  - "python3 inspiderweb.py -d db/test.pickle -s seeds/example_minimal.txt -u bib,refs"
  - "python3 inspiderweb.py --database db/test.pickle --plot --seeds seeds/example_minimal.txt --output build/test.dot"
  - "python3 inspiderweb.py -d db/test.pickle -p -s seeds/example_minimal.txt -o build/test.dot"
  - "python3 inspiderweb.py --database db/test.pickle --plot --examples seeds/example_minimal.txt --updateseeds bib,refs --output build/test.dot"
  - "python3 inspiderweb.py -d db/test.pickle -p -s seeds/example_minimal.txt -u bib,refs -o build/test.dot"
